import { Inter } from "next/font/google";
import NavBar from "@/components/organisms/Navbar";
import "./globals.css";

const inter = Inter({ subsets: ["latin"] });

export const metadata = {
  title: "Spinitu",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body className={`bg-cararra-100 ${inter.className}`}>
        <NavBar />
        <div className="min-h-[calc(100vh-100px)]">{children}</div>
      </body>
    </html>
  );
}
