import { Inter } from 'next/font/google';
import NavBar from '@/components/organisms/Navbar';
import { Toaster } from 'sonner';
import './globals.css';
// import 'material-symbols';
import 'material-symbols/outlined.css';

const inter = Inter({ subsets: ['latin'] });

export const metadata = {
  title: 'Spinitu',
  description: 'Generated by create next app',
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body className={`bg-cararra-100 ${inter.className}`}>
        <NavBar />
        <div className="min-h-[calc(100vh-100px)] px-10 py-5">
          {children}
          <Toaster />
        </div>
      </body>
    </html>
  );
}
